# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16b840b8f872e810f24cd4c435bbeee1de60ac2426b93d4cd303ff95075b483f92c3cb5ed6ceb11d746c20022ca6c2ddf7b7c424169a27ac384868a2578afaba

test:
  secret_key_base: 44415587f4ff5a112e008ec63c208bf2cde41f68dbedfe84e452719313ecd4b7f6a42d5e4c4ce8c19bf11165e8579c369affa2a23fa84cb00752c3b9a242feb9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
